version: '2'

services:
  web:
    build: .
    environment:
      CACHE_DEV_REQUESTS: "true"
      DEFAULT_SOURCE: "local"
      IMAGE_404: "default.jpg"
      LOCAL_FILE_PATH: /images
    ports:
      - "3001:80"
    volumes:
      - ./local_images:/images
